const menu=document.querySelector('.mobile-menu'),sidebar=document.querySelector('.sidebar');
if(document.body.classList.contains('profile-editor'))fetch('/api/auth/me').then(r=>r.json()).then(u=>{if(!u||u.role!=='admin')location.href='admin-login.html'}).catch(()=>location.href='admin-login.html');
if(menu&&sidebar){menu.addEventListener('click',()=>sidebar.classList.toggle('open'));document.addEventListener('click',e=>{if(innerWidth<901&&!sidebar.contains(e.target)&&e.target!==menu)sidebar.classList.remove('open')})}
const sideNav=document.querySelector('.sidebar nav');
const publicLogin=document.querySelector('.topbar .top-cta');if(publicLogin){publicLogin.href='student-login.html';publicLogin.innerHTML='Student login <span>→</span>'}

// Verified professional content supplied from Harsha's LinkedIn export.
const homeArt=document.querySelector('.dashboard-hero .hero-art');
if(homeArt)homeArt.innerHTML='<img class="teacher-hero-photo" src="assets/harsha-profile.jpg" alt="Harsha Madushan"><div class="teacher-caption"><small>YOUR ICT TEACHER</small><b data-profile="name">Harsha Madushan</b><span>BICT · Power BI · Data Analytics</span></div><div class="bubble b1">ICT</div>';
const stats=document.querySelectorAll('.quick-stats>div:not(.next-class)');
if(stats.length===3){stats[0].innerHTML='<span>PROFESSIONAL EXPERIENCE</span><strong>Michelin</strong><small>Professional experience</small>';stats[1].innerHTML='<span>ACADEMIC PATH</span><strong>BICT</strong><small>Uva Wellassa University graduate</small>';stats[2].innerHTML='<span>REAL-WORLD SKILLS</span><strong>Power BI</strong><small>Data analytics & visualization</small>'}
const homeHello=document.querySelector('.topbar .hello');if(homeHello)homeHello.textContent='ආයුබෝවන්, STUDENT 👋';

async function loadProfile(){try{const r=await fetch('/api/profile');if(!r.ok)return;const p=await r.json();document.querySelectorAll('[data-profile="name"]').forEach(x=>x.textContent=p.name);if(p.photo_url)document.querySelectorAll('img[src="assets/harsha-profile.jpg"],#profile-preview-image,.preview-image-wrap img').forEach(x=>x.src=p.photo_url);return p}catch{return null}}
loadProfile();
if(document.body.classList.contains('profile-editor')){const adminAvatar=document.querySelector('.student-top .student-avatar');if(adminAvatar){adminAvatar.setAttribute('role','link');adminAvatar.setAttribute('tabindex','0');adminAvatar.title='Admin profile';const goProfile=()=>location.href='profile.html';adminAvatar.addEventListener('click',goProfile);adminAvatar.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();goProfile()}});loadProfile().then(p=>{if(p?.photo_url)adminAvatar.innerHTML=`<img src="${p.photo_url}" alt="Admin profile">`})}}
async function loadPublicContent(){try{const r=await fetch('/api/public/content');if(!r.ok)return;const d=await r.json();const resourceGrid=document.querySelector('.resource-grid');if(resourceGrid)resourceGrid.innerHTML=d.materials.map(x=>`<article><span class="file-type green">PDF</span><small>${x.category}</small><h3>${x.title}</h3><p>${x.description}</p><a class="download resource-download" href="assets/resources/${encodeURIComponent(x.filename)}" target="_blank">Open PDF ↗</a></article>`).join('');const schedule=document.querySelector('.schedule');if(schedule)schedule.innerHTML=d.sessions.map(x=>`<article data-type="${x.course_type.toLowerCase().replace('/','')}"><time><b>${x.course_type}</b><strong>${(x.session_date||'').slice(-2)}</strong><small>${(x.session_date||'').slice(5,7)}</small></time><div><span>${x.course_type} ICT</span><h3>${x.title}</h3><p>${x.location} · ${x.description}</p></div><strong>${x.time_text}</strong><a href="contact.html">Join ↗</a></article>`).join('');const about=document.querySelector('.about-page>div:last-child>p');if(about)about.textContent=d.content.about_intro;const box=document.querySelector('.signup>div');if(box&&!box.querySelector('.study-copy')){const p=document.createElement('p');p.className='study-copy';p.textContent=d.content.study_letter;box.appendChild(p)}}catch{}}
loadPublicContent();
if(document.querySelector('.class-list'))fetch('/api/public/content').then(r=>r.json()).then(d=>{document.querySelector('.class-list').innerHTML=d.courses.map((x,i)=>`<article><div class="class-visual ${i%2?'ink':'lime'}"><span>0${i+1}</span><b>${i%2?'&lt;/&gt;':'⌁'}</b><small>${x.level}</small></div><div><span class="label">${x.level}</span><h2>${x.title}</h2><p>${x.description}</p><a class="button" href="contact.html">Reserve a seat ↗</a></div></article>`).join('')}).catch(()=>{});

document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.querySelectorAll('.schedule article').forEach(c=>c.hidden=b.dataset.filter!=='all'&&c.dataset.type!==b.dataset.filter)}));
document.querySelectorAll('.download').forEach(b=>b.addEventListener('click',()=>{b.textContent='Coming soon — add your PDF';b.classList.add('done')}));
const signup=document.querySelector('#signup-form');if(signup)signup.addEventListener('submit',async e=>{e.preventDefault();const note=document.querySelector('#form-message'),email=signup.querySelector('input').value;try{const r=await fetch('/api/subscriptions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw Error(d.error);note.textContent='✓ Subscribed! You will receive new ICT lessons.';signup.reset()}catch(x){note.textContent=x.message}});

const contact=document.querySelector('#contact-form');
if(contact)contact.addEventListener('submit',async e=>{e.preventDefault();const inputs=contact.querySelectorAll('input,select,textarea');const payload={student_name:inputs[0].value,phone:inputs[1].value,email:inputs[2].value,class_name:inputs[3].value,message:inputs[4].value};const out=document.querySelector('#contact-message');try{const r=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error);out.textContent='✓ Enquiry saved successfully. Reference #'+data.id;contact.reset()}catch(err){out.textContent='Could not save: '+err.message+'. Please run python server.py.'}});

const profileForm=document.querySelector('#profile-form');
if(profileForm){
  const photoControl=profileForm.querySelector('.photo-control');if(photoControl&&!document.querySelector('#photo-upload')){const uploader=document.createElement('label');uploader.className='profile-photo-upload';uploader.innerHTML='<span>Change teacher photo</span><input id="photo-upload" type="file" accept="image/jpeg,image/png,image/webp">';photoControl.appendChild(uploader)}
  const bioLabel=profileForm.querySelector('textarea[name="bio"]').closest('label');if(!profileForm.elements.linkedin){const linked=document.createElement('label');linked.innerHTML='LinkedIn profile<input name="linkedin" type="url" required>';bioLabel.before(linked)}
  const defaults={name:'Harsha Madushan',title:'BICT Graduate & Business Intelligence Enthusiast',email:'harshamaduushan@gmail.com',phone:'0788523755',location:'Sri Lanka',bio:'BICT graduate and aspiring Business Intelligence Analyst skilled in Power BI, data analysis, visualization and networking. I bring real-world analytics, Python and technology experience into practical ICT learning.',linkedin:'https://www.linkedin.com/in/swhmadushan'};
  const previewName=document.querySelector('#preview-name'),previewTitle=document.querySelector('#preview-title'),previewBio=document.querySelector('#preview-bio'),previewImage=document.querySelector('#profile-preview-image');
  const fill=p=>Object.entries(p).forEach(([k,v])=>{if(profileForm.elements[k])profileForm.elements[k].value=v});const update=()=>{previewName.textContent=profileForm.elements.name.value;previewTitle.textContent=profileForm.elements.title.value;previewBio.textContent=profileForm.elements.bio.value};
  loadProfile().then(p=>{fill(p||defaults);update()});profileForm.addEventListener('input',update);
  document.querySelector('#photo-upload')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(f.size>5*1024*1024){document.querySelector('#profile-message').textContent='Photo must be smaller than 5 MB.';return}const reader=new FileReader();reader.onload=async x=>{previewImage.src=x.target.result;document.querySelector('.preview-image-wrap img').src=x.target.result;const r=await fetch('/api/profile/photo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mime:f.type,data:x.target.result.split(',')[1]})});const result=await r.json();document.querySelector('#profile-message').textContent=r.ok?'✓ Teacher photo saved.':result.error};reader.readAsDataURL(f)});
  profileForm.addEventListener('submit',async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(profileForm));delete payload.photo;const msg=document.querySelector('#profile-message');try{const r=await fetch('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error);msg.textContent='✓ Profile saved to database.'}catch(err){msg.textContent='Could not save: '+err.message+'. Run python server.py.'}});
  document.querySelector('#reset-profile').addEventListener('click',()=>{fill(defaults);update()});
}

const enquiryList=document.querySelector('#enquiry-list');
async function loadEnquiries(){if(!enquiryList)return;try{const r=await fetch('/api/enquiries');if(!r.ok)throw Error('API unavailable');const rows=await r.json();enquiryList.innerHTML=rows.length?rows.map(x=>`<article class="enquiry-item"><span class="enquiry-id">#${x.id}</span><div><h3>${x.student_name}</h3><span class="enquiry-meta">${x.class_name} · ${x.created_at}</span><p>${x.message||'No additional message.'}</p></div><div class="enquiry-contact"><b>${x.phone}</b><span>${x.email||'No email provided'}</span><button class="delete-enquiry" data-delete-enquiry="${x.id}">Delete</button></div></article>`).join(''):'<p class="empty-state">No enquiries yet. Submit the contact form to test the database.</p>'}catch{enquiryList.innerHTML='<p class="empty-state">Database server is not running. Start it with: python server.py</p>'}}
if(enquiryList){enquiryList.addEventListener("click",async e=>{const b=e.target.closest("[data-delete-enquiry]");if(b&&confirm("Delete this enquiry?")){await fetch("/api/admin/enquiries/"+b.dataset.deleteEnquiry,{method:"DELETE"});loadEnquiries()}});loadEnquiries();document.querySelector('#refresh-enquiries').addEventListener('click',loadEnquiries)}

// Refined public and student experience.
document.querySelectorAll('.sidebar nav a[href="about.html"]').forEach(a=>a.innerHTML='<i>◎</i>About Your Teacher');
if(document.body.classList.contains('student-area')&&sideNav&&!sideNav.querySelector('a[href="about.html"],a[href="student-about.html"]')){const logout=sideNav.querySelector('[data-logout]');const teacherLink=document.createElement('a');teacherLink.href='student-about.html';teacherLink.innerHTML='<i>◎</i>About Your Teacher';sideNav.insertBefore(teacherLink,logout)}
if(homeArt){
  const caption=homeArt.querySelector('.teacher-caption span');
  if(caption)caption.textContent='Bachelor of Information and Communication Technology Honours (BICT) at Uva Wellassa University';
}
document.querySelector('.quick-stats')?.remove();

function safeText(value){return String(value??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function resourceSection(category){const c=String(category||'').toUpperCase();if(c.includes('O/L'))return 'ol';if(c.includes('DIAMOND'))return 'diamond';return 'al'}
async function renderRefinedContent(){
  try{
    const r=await fetch('/api/public/content');if(!r.ok)return;const d=await r.json();
    const classList=document.querySelector('.class-list');
    if(classList)classList.innerHTML=d.courses.map((x,i)=>{const online=/online/i.test(x.title)||/online/i.test(x.level);const icon=online?'▣':i===1?'&lt;/&gt;':'01';const colour=online?'blue':i%2?'ink':'lime';return `<article><div class="class-visual ${colour}"><span>0${i+1}</span><b>${icon}</b><small>${safeText(x.level)}</small></div><div><span class="label">${safeText(x.level)}</span><h2>${safeText(x.title)}</h2><p>${safeText(x.description)}</p><a class="button" href="contact.html">Ask about this class ↗</a></div></article>`}).join('');
    const schedule=document.querySelector('.schedule');
    if(schedule)schedule.innerHTML=d.sessions.map(x=>`<article data-type="${safeText(x.course_type.toLowerCase().replace('/',''))}"><time><b>${safeText(x.course_type)}</b><strong>${safeText((x.session_date||'').slice(-2))}</strong><small>${safeText((x.session_date||'').slice(5,7))}</small></time><div><span>${safeText(x.course_type)} ICT</span><h3>${safeText(x.title)}</h3><p>${safeText(x.location)} · ${safeText(x.description)}</p></div><strong>${safeText(x.time_text)}</strong><button class="join-status" type="button">Class access ↗</button></article>`).join('');
    const resourceGrid=document.querySelector('.resource-grid');
    if(resourceGrid){
      resourceGrid.classList.add('organised-resources');
      resourceGrid.innerHTML=`<div class="resource-tabs"><button class="selected" data-resource-filter="ol">O/L Resources</button><button data-resource-filter="al">A/L Resources</button><button data-resource-filter="diamond">Diamond</button></div><div class="resource-section" data-resource-section="ol"><div class="resource-section-head"><span>GRADE 6–11</span><h2>O/L ICT resources</h2><p>Notes, learning outcomes and revision material organised for O/L students.</p></div><div class="resource-cards">${d.materials.filter(x=>resourceSection(x.category)==='ol').map(resourceCard).join('')||emptyResources('O/L')}</div></div><div class="resource-section" data-resource-section="al" hidden><div class="resource-section-head"><span>ADVANCED LEVEL</span><h2>A/L ICT resources</h2><p>Structured theory, technical notes and exam-focused learning material.</p></div><div class="resource-cards">${d.materials.filter(x=>resourceSection(x.category)==='al').map(resourceCard).join('')||emptyResources('A/L')}</div></div><div class="resource-section diamond-section" data-resource-section="diamond" hidden><div class="diamond-mark">◆</div><span>DIAMOND LIBRARY</span><h2>Premium learning is coming soon.</h2><p>Curated lesson packs, guided paper discussions and advanced revision collections are being prepared.</p><button class="diamond-soon" type="button">Notify me when available</button><small class="diamond-message"></small></div>`;
    }
  }catch{}
}
function resourceCard(x){return `<article><span class="file-type green">PDF</span><small>${safeText(x.category)}</small><h3>${safeText(x.title)}</h3><p>${safeText(x.description)}</p><a class="download resource-download" data-resource-level="${resourceSection(x.category)}" data-resource-file="assets/resources/${encodeURIComponent(x.filename)}" href="student-login.html">Log in to download ↗</a></article>`}
function emptyResources(level){return `<p class="resource-empty">No ${level} resources have been published yet. Please check again soon.</p>`}
document.addEventListener('click',e=>{
  const join=e.target.closest('.join-status');if(join){join.closest('article').querySelector('.class-message')?.remove();const note=document.createElement('p');note.className='class-message';note.textContent='This class is not open for online access yet. Class details will be announced soon.';join.closest('article').appendChild(note)}
  const tab=e.target.closest('[data-resource-filter]');if(tab){document.querySelectorAll('[data-resource-filter]').forEach(b=>b.classList.toggle('selected',b===tab));document.querySelectorAll('[data-resource-section]').forEach(s=>s.hidden=s.dataset.resourceSection!==tab.dataset.resourceFilter)}
  if(e.target.closest('.diamond-soon')){document.querySelector('.diamond-message').textContent='Coming soon — this section is not accepting payments yet.'}
});
document.addEventListener('click',async e=>{const link=e.target.closest('.resource-download');if(!link)return;e.preventDefault();let user=null;try{const r=await fetch('/api/auth/me');user=await r.json()}catch{}if(!user||user.role!=='student'){location.href='student-login.html';return}const needed=link.dataset.resourceLevel==='ol'?'O/L':'A/L';if((user.student_stream||'').toUpperCase()!==needed){showResourceGate(`This file is for ${needed} students. Your account is registered for ${user.student_stream||'another'} programme.`);return}window.open(link.dataset.resourceFile,'_blank')});
function showResourceGate(message){let modal=document.querySelector('.resource-gate');if(!modal){modal=document.createElement('div');modal.className='resource-gate';modal.innerHTML='<div role="dialog" aria-modal="true" aria-labelledby="gate-title"><button class="gate-close" aria-label="Close">×</button><span>LOCKED RESOURCE</span><h2 id="gate-title">Sign in to continue.</h2><p></p><a href="student-login.html">Student login →</a><a class="gate-register" href="register.html">Create account</a></div>';document.body.appendChild(modal);modal.addEventListener('click',x=>{if(x.target===modal||x.target.closest('.gate-close'))modal.remove()})}modal.querySelector('p').textContent=message}
renderRefinedContent();
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="quiz.css"><link rel="stylesheet" href="quiz-results.css">');
document.querySelectorAll('body.student-area .student-side nav').forEach(nav=>{if(nav.querySelector('a[href="student-quizzes.html"]'))return;const notices=nav.querySelector('a[href="student-announcements.html"]');const link=document.createElement('a');link.href='student-quizzes.html';link.innerHTML='<i>?</i><span>Quizzes</span>';if(notices)nav.insertBefore(link,notices);else nav.appendChild(link)});
document.querySelectorAll('body.profile-editor .sidebar nav').forEach(nav=>{if(nav.querySelector('a[href="quiz-admin.html"]'))return;const profile=nav.querySelector('a[href="profile.html"]');const link=document.createElement('a');link.href='quiz-admin.html';link.innerHTML='<i>?</i>Quiz Manager';if(profile)nav.insertBefore(link,profile);else nav.appendChild(link)});
