const menu=document.querySelector('.mobile-menu'),sidebar=document.querySelector('.sidebar');
if(document.body.classList.contains('profile-editor'))fetch('/api/auth/me').then(r=>r.json()).then(u=>{if(!u||u.role!=='admin')location.href='admin-login.html'}).catch(()=>location.href='admin-login.html');
if(menu&&sidebar){menu.addEventListener('click',()=>sidebar.classList.toggle('open'));document.addEventListener('click',e=>{if(innerWidth<901&&!sidebar.contains(e.target)&&e.target!==menu)sidebar.classList.remove('open')})}
const sideNav=document.querySelector('.sidebar nav');
const publicLogin=document.querySelector('.topbar .top-cta');if(publicLogin){publicLogin.href='student-login.html';publicLogin.innerHTML='Student login <span>→</span>'}

// Verified professional content supplied from Harsha's LinkedIn export.
const homeArt=document.querySelector('.dashboard-hero .hero-art');
if(homeArt)homeArt.innerHTML='<img class="teacher-hero-photo" src="assets/harsha-profile.jpg" alt="Harsha Madushan"><div class="teacher-caption"><small>YOUR ICT TEACHER</small><b data-profile="name">Harsha Madushan</b><span>BICT · Power BI · Data Analytics</span></div><div class="bubble b1">ICT</div>';
const stats=document.querySelectorAll('.quick-stats>div:not(.next-class)');
if(stats.length===3){stats[0].innerHTML='<span>PROFESSIONAL EXPERIENCE</span><strong>Michelin</strong><small>Professional experience</small>';stats[1].innerHTML='<span>ACADEMIC PATH</span><strong>BICT</strong><small>Uva Wellassa University graduate</small>';stats[2].innerHTML='<span>REAL-WORLD SKILLS</span><strong>Power BI</strong><small>Data analytics & visualization</small>'}
const homeHello=document.querySelector('.topbar .hello');if(homeHello)homeHello.textContent='ආයුබෝවන්, STUDENT 👋';

async function loadProfile(){try{const r=await fetch('/api/profile');if(!r.ok)return;const p=await r.json();document.querySelectorAll('[data-profile="name"]').forEach(x=>x.textContent=p.name);return p}catch{return null}}
loadProfile();
async function loadPublicContent(){try{const r=await fetch('/api/public/content');if(!r.ok)return;const d=await r.json();const resourceGrid=document.querySelector('.resource-grid');if(resourceGrid)resourceGrid.innerHTML=d.materials.map(x=>`<article><span class="file-type green">PDF</span><small>${x.category}</small><h3>${x.title}</h3><p>${x.description}</p><a class="download resource-download" href="assets/resources/${encodeURIComponent(x.filename)}" target="_blank">Open PDF ↗</a></article>`).join('');const schedule=document.querySelector('.schedule');if(schedule)schedule.innerHTML=d.sessions.map(x=>`<article data-type="${x.course_type.toLowerCase().replace('/','')}"><time><b>${x.course_type}</b><strong>${(x.session_date||'').slice(-2)}</strong><small>${(x.session_date||'').slice(5,7)}</small></time><div><span>${x.course_type} ICT</span><h3>${x.title}</h3><p>${x.location} · ${x.description}</p></div><strong>${x.time_text}</strong><a href="contact.html">Join ↗</a></article>`).join('');const about=document.querySelector('.about-page>div:last-child>p');if(about)about.textContent=d.content.about_intro;const box=document.querySelector('.signup>div');if(box&&!box.querySelector('.study-copy')){const p=document.createElement('p');p.className='study-copy';p.textContent=d.content.study_letter;box.appendChild(p)}}catch{}}
loadPublicContent();
if(document.querySelector('.class-list'))fetch('/api/public/content').then(r=>r.json()).then(d=>{document.querySelector('.class-list').innerHTML=d.courses.map((x,i)=>`<article><div class="class-visual ${i%2?'ink':'lime'}"><span>0${i+1}</span><b>${i%2?'&lt;/&gt;':'⌁'}</b><small>${x.level}</small></div><div><span class="label">${x.level}</span><h2>${x.title}</h2><p>${x.description}</p><a class="button" href="contact.html">Reserve a seat ↗</a></div></article>`).join('')}).catch(()=>{});

document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');document.querySelectorAll('.schedule article').forEach(c=>c.hidden=b.dataset.filter!=='all'&&c.dataset.type!==b.dataset.filter)}));
document.querySelectorAll('.download').forEach(b=>b.addEventListener('click',()=>{b.textContent='Coming soon — add your PDF';b.classList.add('done')}));
const signup=document.querySelector('#signup-form');if(signup)signup.addEventListener('submit',async e=>{e.preventDefault();const note=document.querySelector('#form-message'),email=signup.querySelector('input').value;try{const r=await fetch('/api/subscriptions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw Error(d.error);note.textContent='✓ Subscribed! You will receive new ICT lessons.';signup.reset()}catch(x){note.textContent=x.message}});

const contact=document.querySelector('#contact-form');
if(contact)contact.addEventListener('submit',async e=>{e.preventDefault();const inputs=contact.querySelectorAll('input,select,textarea');const payload={student_name:inputs[0].value,phone:inputs[1].value,email:inputs[2].value,class_name:inputs[3].value,message:inputs[4].value};const out=document.querySelector('#contact-message');try{const r=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error);out.textContent='✓ Enquiry saved successfully. Reference #'+data.id;contact.reset()}catch(err){out.textContent='Could not save: '+err.message+'. Please run python server.py.'}});

const profileForm=document.querySelector('#profile-form');
if(profileForm){
  const bioLabel=profileForm.querySelector('textarea[name="bio"]').closest('label');if(!profileForm.elements.linkedin){const linked=document.createElement('label');linked.innerHTML='LinkedIn profile<input name="linkedin" type="url" required>';bioLabel.before(linked)}
  const defaults={name:'Harsha Madushan',title:'BICT Graduate & Business Intelligence Enthusiast',email:'harshamaduushan@gmail.com',phone:'0788523755',location:'Sri Lanka',bio:'BICT graduate and aspiring Business Intelligence Analyst skilled in Power BI, data analysis, visualization and networking. I bring real-world analytics, Python and technology experience into practical ICT learning.',linkedin:'https://www.linkedin.com/in/swhmadushan'};
  const previewName=document.querySelector('#preview-name'),previewTitle=document.querySelector('#preview-title'),previewBio=document.querySelector('#preview-bio'),previewImage=document.querySelector('#profile-preview-image');
  const fill=p=>Object.entries(p).forEach(([k,v])=>{if(profileForm.elements[k])profileForm.elements[k].value=v});const update=()=>{previewName.textContent=profileForm.elements.name.value;previewTitle.textContent=profileForm.elements.title.value;previewBio.textContent=profileForm.elements.bio.value};
  loadProfile().then(p=>{fill(p||defaults);update()});profileForm.addEventListener('input',update);
  document.querySelector('#photo-upload').addEventListener('change',e=>{const f=e.target.files[0];if(f){const reader=new FileReader();reader.onload=x=>{previewImage.src=x.target.result;document.querySelector('.preview-image-wrap img').src=x.target.result};reader.readAsDataURL(f)}});
  profileForm.addEventListener('submit',async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(profileForm));delete payload.photo;const msg=document.querySelector('#profile-message');try{const r=await fetch('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error);msg.textContent='✓ Profile saved to database.'}catch(err){msg.textContent='Could not save: '+err.message+'. Run python server.py.'}});
  document.querySelector('#reset-profile').addEventListener('click',()=>{fill(defaults);update()});
}

const enquiryList=document.querySelector('#enquiry-list');
async function loadEnquiries(){if(!enquiryList)return;try{const r=await fetch('/api/enquiries');if(!r.ok)throw Error('API unavailable');const rows=await r.json();enquiryList.innerHTML=rows.length?rows.map(x=>`<article class="enquiry-item"><span class="enquiry-id">#${x.id}</span><div><h3>${x.student_name}</h3><span class="enquiry-meta">${x.class_name} · ${x.created_at}</span><p>${x.message||'No additional message.'}</p></div><div class="enquiry-contact"><b>${x.phone}</b><span>${x.email||'No email provided'}</span><button class="delete-enquiry" data-delete-enquiry="${x.id}">Delete</button></div></article>`).join(''):'<p class="empty-state">No enquiries yet. Submit the contact form to test the database.</p>'}catch{enquiryList.innerHTML='<p class="empty-state">Database server is not running. Start it with: python server.py</p>'}}
if(enquiryList){enquiryList.addEventListener("click",async e=>{const b=e.target.closest("[data-delete-enquiry]");if(b&&confirm("Delete this enquiry?")){await fetch("/api/admin/enquiries/"+b.dataset.deleteEnquiry,{method:"DELETE"});loadEnquiries()}});loadEnquiries();document.querySelector('#refresh-enquiries').addEventListener('click',loadEnquiries)}
